### ISSUE TITLE
CAR_INLA and categorical variable covariates 

### ISSUE THREAD

**Issue by seyiaros** [spatialstatisticsupna/bigDM#5] opened 2024-02-08 11:48 UTC
Hi 

I have been trying to specify a model formula that will allow me to include different levels of categorical covariates using CAR_INLA. Seems this is not supported by CAR_INLA. I am trying to see how the estimates of the covariates change from a reference category. When I try using a factor variable within the CAR_INLA function, I get an error message " x must be numeric". Is there any way to solve this?

**Comment by aritz-adin** [comment] 2024-02-12 08:11
Duplicate of #4

**Closed as completed by aritz-adin** 2024-02-12 08:11 UTC
